/**
 * Tweak the display of pages generated by sphinx-gallery.
 *
 * For actual example pages generated by sphinx-gallery, this script essentially
 * removes the note "Go to the end..." at the top of the page, and instead move the
 * jupyterlite, binder, and download buttons to the secondary sidebar.
 *
 * For the index pages, the script removes the secondary sidebar. The reason why this
 * is not done in conf.py is that we cannot have multiple widecard matches, while we
 * must have the "**" one that matches all pages.
 *
 * Note: this script should be included only in pages generated by sphinx-gallery to
 * avoid any potential conflicts.
 */

function tweakGalleryDisplay() {
  if (location.pathname.endsWith("index.html")) {
    // Grab and remove the secondary sidebar
    const secondarySidebarContainer = document.querySelector(
      ".bd-sidebar-secondary.bd-toc"
    );
    if (secondarySidebarContainer) {
      secondarySidebarContainer.remove();
    }

    // Grab and remove the toggle button for the secondary sidebar
    const secondarySidebarToggleButton = document.querySelector(
      ".sidebar-toggle.secondary-toggle"
    );
    if (secondarySidebarToggleButton) {
      secondarySidebarToggleButton.remove();
    }

    return;
  }

  // Remove the note at the top of the page
  const sgNote = document.querySelector(".sphx-glr-download-link-note");
  sgNote.remove();

  // Grab the footer for information and the secondary sidebar
  const sgFooter = document.querySelector(".sphx-glr-footer");
  const secondarySidebar = document.querySelector(".sidebar-secondary-items");

  function appendSecondarySidebarComponent(items) {
    // Each item in the items array should have "element" and "title" (can be null)
    var newSecondarySidebarItem = document.createElement("div");
    newSecondarySidebarItem.className = "sidebar-secondary-item";
    items.forEach((item) => {
      var newItemContainer = document.createElement("div");
      newItemContainer.appendChild(item.element);
      if (item.title) {
        newItemContainer.title = item.title;
      }
      newSecondarySidebarItem.appendChild(newItemContainer);
    });
    secondarySidebar.appendChild(newSecondarySidebarItem);
  }

  function createSidebarDownloadLink(downloadLink, isJupyter = false) {
    // Create a new reference item
    var newLink = document.createElement("a");
    newLink.className = "reference internal";
    newLink.href = downloadLink.href;
    newLink.setAttribute("download", "");

    // Add the download icon to the new reference item
    var newIcon = document.createElement("i");
    newIcon.className = "fa-solid fa-download";
    newLink.appendChild(newIcon);

    // Add some text to the new reference item
    const linkType = isJupyter ? "Jupyter notebook" : "source code";
    var newText = document.createTextNode(`Download ${linkType}`);
    newLink.appendChild(newText);

    // Get the file name, expected to be in the last span element of the download link
    var title = null;
    const fileNameSpan = downloadLink.querySelector("span:last-child");
    if (fileNameSpan) {
      title = fileNameSpan.textContent;
    }

    return { element: newLink, title: title };
  }

  function createSidebarBadgeLink(badgeLink) {
    // Create a new reference item
    var newLink = document.createElement("a");
    newLink.className = "reference external";
    newLink.href = badgeLink.href;

    // Add an image with same alt and src to the new reference item, except that the
    // height is fixed to a smaller value to fit the secondary sidebar better
    const img = badgeLink.querySelector("img");
    var newImg = document.createElement("img");
    newImg.alt = img.alt;
    newImg.src = img.src;
    newImg.height = 20;
    newLink.appendChild(newImg);

    return { element: newLink, title: null };
  }

  // Remove the sourcelink component in the secondary sidebar if it exists
  const sourceLink = secondarySidebar.querySelector(
    ".sidebar-secondary-item .tocsection.sourcelink"
  );
  if (sourceLink) {
    sourceLink.parentElement.remove();
  }

  // Move stuff all to the secondary sidebar
  appendSecondarySidebarComponent([
    createSidebarDownloadLink(
      sgFooter.querySelector(".sphx-glr-download-python a")
    ),
    createSidebarDownloadLink(
      sgFooter.querySelector(".sphx-glr-download-jupyter a"),
      (isJupyter = true)
    ),
  ]);
  appendSecondarySidebarComponent([
    createSidebarBadgeLink(sgFooter.querySelector(".lite-badge a")),
    createSidebarBadgeLink(sgFooter.querySelector(".binder-badge a")),
  ]);

  // Remove the whole footer, assumed to contain only those links that we have moved
  sgFooter.remove();
}

document.addEventListener("DOMContentLoaded", tweakGalleryDisplay);
